apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: java-demo-app-servicemonitor
  namespace: monitoring
  labels:
    k8s.observability.servicemonitor: "true"
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - java-app-ns
  selector:
    matchLabels:
      app: java-demo-app
  endpoints:
    - port: http-metrics
      interval: 15s
      path: /actuator/prometheus
