apiVersion: v1
kind: Service
metadata:
  name: java-demo-service
  namespace: java-app-ns
spec:
  selector:
    app: java-demo-app
  ports:
    - name: http-metrics
      port: 8085
      targetPort: 8085
