apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: java-demo-app-servicemonitor
  namespace: java-app-ns
  labels:
    k8s.observability.servicemonitor: "true"
spec:
  selector:
    matchLabels:
      app: java-demo-app
  endpoints:
    - port: http-metrics
      interval: 15s
      path: /actuator/prometheus
