apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: k6
    repo: https://grafana.github.io/helm-charts
    version: 6.6.0
    releaseName: k6
    namespace: monitoring
    valuesFile: values.yaml
