apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: k6
    repo: https://grafana.github.io/helm-charts
    version: 4.2.0
    releaseName: k6
    namespace: monitoring
    valuesFile: values.yaml

resources:
  - k6-cm.yaml

# Create a ConfigMap from the k6 script file
configMapGenerator:
  - name: loki-test-script
    files:
      - loki-test.js
    # This will prevent Kustomize from adding a hash to the ConfigMap name
    options:
      disableNameSuffixHash: true
