name: Java Secure CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }} # uses the format owner/repo

jobs:
  # --- JOB 1: BUILD, TEST & SECURITY ---
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write # Necessary for uploading security results
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
          cache-dependency-path: app/pom.xml

      # 1. Build the Application with Maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        working-directory: app
      # 2. Security: Trivy Filesystem Scan (Searches for secrets and vulnerabilities in code/dependencies)
      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          ignore-unfixed: true
          format: "table"
          exit-code: "1" # Fail the job if vulnerabilities are found
          severity: "CRITICAL,HIGH"

      # 3. Save the JAR for the next job (Avoids recompiling)
      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-artifact
          path: app/target/*.jar
          retention-days: 1

  # --- JOB 2: DOCKER BUILD & PUSH ---
  docker-publish:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event_name != 'pull_request'
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      #  1. Download JAR Artifact from previous job
      - name: Download JAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: app-artifact
          path: app/target/

      # 2. Login no GitHub Container Registry
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Prepare Metadata (Automatic Tags)
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=long  # Tag with the commit SHA (immutable)
            type=raw,value=latest # Tag latest

      # 4. Build and Push
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
