name: Infrastructure Deployment (Terraform)
on:
  workflow_dispatch:
    inputs:
      terraform_action:
        description: "Terraform action to perform"
        required: true
        default: "plan"
        type: choice
        options:
          - plan
          - apply
          - destroy
  # pull_request:
  #   branches:
  #     - main
  #   paths:
  #     - "infra/**"
permissions:
  contents: read
  pull-requests: write # writes the terraform plan results to PRs
jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Terraform plan
        id: plan
        if: github.event.inputs.terraform_action == 'plan'
        run: |
          terraform plan -out=tfplan
      - name: Terraform plan status
        if: steps.plan.outcome == 'failure'
        run: exit 1
      - name: Terraform apply
        if: github.event.inputs.terraform_action == 'apply'
        run: |
          terraform init
          terraform apply -auto-approve -input=false tfplan
      - name: Terraform destroy
        if: github.event.inputs.terraform_action == 'destroy'
        run: |
          terraform init
          terraform destroy -auto-approve -input=false
