name: Manual Load Test (k6)

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: "URL da Aplicação para atacar"
        required: true
        default: "http://localhost:8085/actuator/health"
      vus:
        description: "Virtual Users (Carga)"
        required: true
        default: "10"
      duration:
        description: "Duração do teste"
        required: true
        default: "30s"

jobs:
  attack:
    name: Disparar k6
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run k6 Test
        uses: grafana/k6-action@v0.3.0
        with:
          filename: tests/load-test.js
          flags: --vus ${{ inputs.vus }} --duration ${{ inputs.duration }}
        env:
          TARGET_URL: ${{ inputs.target_url }}
